export const TELEMETRY_SECTOR_COUNT = 3;
export const TIMING_HISTORY_WINDOW_SECONDS = 18;
export const TIMING_HISTORY_MAX_SAMPLES = 720;
export const TIMING_LINE_TARGET_SPACING_METERS = 175;
export const TIMING_LINE_HISTORY_LAPS = 3;
