export const TRACK_RAY_STEP_METERS = 1;
export const TRACK_RAY_REFINE_STEPS = 12;
export const DRIVER_RAY_REFINE_STEPS = 0;
export const ANALYTIC_TRACK_RAY_MAX_CURVATURE = 0.00005;
export const PIT_CONNECTOR_RAY_FALLBACK_METERS = 55;
export const DEFAULT_RAY_ANGLES_DEGREES = [-135, -60, -20, 0, 20, 60, 135, 180];
