export const TRAINING_DEMO_DRIVERS = [
  {
    id: 'budget',
    code: 'BUD',
    icon: 'BB',
    name: 'Budget Buddy',
    color: '#ff2d55',
    tire: 'M',
    raceData: ['AI finance coach', 'Python + LLM', 'Budget guardrails'],
  },
  {
    id: 'noir',
    code: 'NOI',
    icon: 'NN',
    name: 'Neural Noir',
    color: '#ffb000',
    tire: 'M',
    raceData: ['Procedural mystery', 'Gemini storytelling', 'Unreal loop'],
  },
  {
    id: 'vinyl',
    code: 'HOL',
    icon: 'HV',
    name: 'HoloVinyl',
    color: '#00c2a8',
    tire: 'H',
    raceData: ['Touchless DJ control', 'Computer vision', 'Hand tracking'],
  },
  {
    id: 'drsorriso',
    code: 'DRS',
    icon: 'DR',
    name: 'DrSorrisoDonations',
    color: '#e10600',
    tire: 'S',
    raceData: ['Donation intake', 'Database workflow', 'Automation tool'],
  },
  {
    id: 'victoria',
    code: 'VIC',
    icon: 'VI',
    name: 'VictorIA',
    color: '#00a3ff',
    tire: 'M',
    raceData: ['Game AI sandbox', 'Robotics ideas', 'Vision systems'],
  },
  {
    id: 'reminderz',
    code: 'REM',
    icon: 'RZ',
    name: 'ReminderZ',
    color: '#a3e635',
    tire: 'H',
    raceData: ['Knowledge workflow', 'Personal graph', 'Capture tool'],
  },
  {
    id: 'clipclop',
    code: 'CLP',
    icon: 'CC',
    name: 'ClipClop',
    color: '#f97316',
    tire: 'S',
    raceData: ['Mac + Android sync', 'Local clipboard', 'Productivity app'],
  },
  {
    id: 'core',
    code: 'COR',
    icon: 'AI',
    name: 'Core Conflict',
    color: '#38bdf8',
    tire: 'M',
    raceData: ['Runtime AI agents', 'Multiplayer state', 'Game systems'],
  },
];

export const TRAINING_DEMO_ENTRIES = [
  {
    driverId: 'budget',
    driverNumber: 71,
    timingName: 'Budget',
    driver: { pace: 52, racecraft: 74, aggression: 38, riskTolerance: 47, patience: 81, consistency: 86 },
    vehicle: { id: 'budget-bb01', name: 'BB-01 Ledger', power: 48, braking: 72, aero: 55, dragEfficiency: 66, mechanicalGrip: 63, weightControl: 58, tireCare: 82 },
  },
  {
    driverId: 'noir',
    driverNumber: 13,
    timingName: 'Noir',
    driver: { pace: 68, racecraft: 83, aggression: 61, riskTolerance: 72, patience: 57, consistency: 64 },
    vehicle: { id: 'noir-nn13', name: 'NN-13 Shadow', power: 64, braking: 60, aero: 73, dragEfficiency: 57, mechanicalGrip: 69, weightControl: 54, tireCare: 51 },
  },
  {
    driverId: 'vinyl',
    driverNumber: 33,
    timingName: 'HoloVinyl',
    driver: { pace: 71, racecraft: 66, aggression: 52, riskTolerance: 59, patience: 62, consistency: 58 },
    vehicle: { id: 'vinyl-hv33', name: 'HV-33 Groove', power: 70, braking: 49, aero: 58, dragEfficiency: 74, mechanicalGrip: 52, weightControl: 68, tireCare: 46 },
  },
  {
    driverId: 'drsorriso',
    driverNumber: 55,
    timingName: 'DrSorriso',
    driver: { pace: 46, racecraft: 69, aggression: 44, riskTolerance: 43, patience: 76, consistency: 73 },
    vehicle: { id: 'sorriso-ds55', name: 'DS-55 Intake', power: 54, braking: 67, aero: 62, dragEfficiency: 49, mechanicalGrip: 71, weightControl: 45, tireCare: 69 },
  },
  {
    driverId: 'victoria',
    driverNumber: 11,
    timingName: 'VictorIA',
    driver: { pace: 78, racecraft: 79, aggression: 58, riskTolerance: 65, patience: 55, consistency: 68 },
    vehicle: { id: 'victoria-vi11', name: 'VI-11 Vector', power: 76, braking: 58, aero: 65, dragEfficiency: 63, mechanicalGrip: 61, weightControl: 60, tireCare: 48 },
  },
  {
    driverId: 'reminderz',
    driverNumber: 7,
    timingName: 'ReminderZ',
    driver: { pace: 41, racecraft: 61, aggression: 34, riskTolerance: 39, patience: 85, consistency: 80 },
    vehicle: { id: 'reminderz-rz07', name: 'RZ-07 Recall', power: 42, braking: 76, aero: 50, dragEfficiency: 72, mechanicalGrip: 58, weightControl: 63, tireCare: 88 },
  },
  {
    driverId: 'clipclop',
    driverNumber: 14,
    timingName: 'ClipClop',
    driver: { pace: 73, racecraft: 88, aggression: 76, riskTolerance: 78, patience: 48, consistency: 61 },
    vehicle: { id: 'clipclop-cc14', name: 'CC-14 Sync', power: 68, braking: 63, aero: 59, dragEfficiency: 61, mechanicalGrip: 78, weightControl: 56, tireCare: 44 },
  },
  {
    driverId: 'core',
    driverNumber: 91,
    timingName: 'Core',
    driver: { pace: 82, racecraft: 85, aggression: 67, riskTolerance: 74, patience: 53, consistency: 72 },
    vehicle: { id: 'core-ai91', name: 'AI-91 Core', power: 80, braking: 61, aero: 72, dragEfficiency: 59, mechanicalGrip: 75, weightControl: 51, tireCare: 50 },
  },
];
