import { serializeParticipantInteraction } from '../participants/participantInteractions.js';

export function finiteOrNull(value) {
  return Number.isFinite(value) ? value : null;
}

export function serializeWheels(wheels = []) {
  return wheels.map((wheel) => ({
    id: wheel.id,
    x: wheel.x,
    y: wheel.y,
    signedOffset: wheel.signedOffset,
    crossTrackError: wheel.crossTrackError,
    surface: wheel.surface,
    onTrack: Boolean(wheel.onTrack),
    inPitLane: Boolean(wheel.inPitLane),
    fullyOutsideWhiteLine: Boolean(wheel.fullyOutsideWhiteLine),
  }));
}

export function serializeCar(car, rank, penaltySeconds = 0, dependencies) {
  const {
    createLapTelemetry,
    normalizePitIntent,
    PIT_INTENT_NONE,
    serializeLapTelemetry,
    serializePitStop,
    simSpeedToKph,
    simUnitsToMeters,
    VEHICLE_LIMITS,
  } = dependencies;
  const finishTime = car.finishTime ?? null;
  const raceStatus = car.finished ? 'waved-flag' : 'racing';
  return {
    id: car.id,
    code: car.code,
    timingCode: car.timingCode,
    driverNumber: car.driverNumber,
    icon: car.icon,
    raceName: car.raceName,
    name: car.name,
    color: car.color,
    team: car.team ? { ...car.team } : null,
    tire: car.tire,
    personality: { ...car.personality },
    aggression: car.aggression,
    aggressionPercent: Math.round((car.aggression ?? 0) * 100),
    setup: {
      vehicleId: car.vehicleId,
      vehicleName: car.vehicleName,
      vehicleRatings: car.vehicleRatings ? { ...car.vehicleRatings } : null,
      maxSpeedKph: simSpeedToKph(VEHICLE_LIMITS.maxSpeed),
      powerUnitKn: car.powerNewtons / 1000,
      brakeSystemKn: car.brakeNewtons / 1000,
      dragCoefficient: car.dragCoefficient,
      downforceCoefficient: car.downforceCoefficient,
      tireGrip: car.tireGrip,
      tireCare: car.tireCare,
      massKg: car.mass,
      pace: car.pace,
      racecraft: car.racecraft,
    },
    interaction: serializeParticipantInteraction(car.interaction),
    rank,
    classifiedRank: car.classifiedRank ?? rank,
    finishRank: car.finishRank ?? null,
    status: raceStatus,
    raceStatus,
    wavedFlag: Boolean(car.finished),
    finished: Boolean(car.finished),
    finishTime,
    penaltySeconds,
    adjustedFinishTime: finishTime == null ? null : finishTime + penaltySeconds,
    previousX: car.previousX ?? car.x,
    previousY: car.previousY ?? car.y,
    x: car.x,
    y: car.y,
    previousHeading: car.previousHeading ?? car.heading,
    heading: car.heading,
    steeringAngle: car.steeringAngle,
    yawRate: car.yawRate,
    turnRadius: car.turnRadius,
    speed: car.speed,
    speedKph: simSpeedToKph(car.speed),
    throttle: car.throttle,
    brake: car.brake,
    lateralAcceleration: car.lateralAcceleration,
    progress: car.progress,
    raceDistance: car.raceDistance,
    distanceMeters: simUnitsToMeters(car.raceDistance),
    lap: car.lap,
    lapTelemetry: serializeLapTelemetry(car.lapTelemetry ?? createLapTelemetry({ length: 1 }, 0, 0)),
    gapAhead: car.gapAhead,
    gapAheadMeters: Number.isFinite(car.gapAhead) ? simUnitsToMeters(car.gapAhead) : Infinity,
    gapAheadSeconds: car.gapAheadSeconds,
    intervalAheadSeconds: car.intervalAheadSeconds,
    leaderGapSeconds: car.leaderGapSeconds,
    gapAheadLaps: car.gapAheadLaps ?? 0,
    intervalAheadLaps: car.intervalAheadLaps ?? car.gapAheadLaps ?? 0,
    leaderGapLaps: car.leaderGapLaps ?? 0,
    drsEligible: car.drsEligible,
    drsActive: car.drsActive,
    drsZoneId: car.drsZoneId,
    drsZoneEnabled: car.drsZoneEnabled,
    canAttack: car.canAttack,
    signedOffset: car.trackState?.signedOffset ?? 0,
    crossTrackError: car.trackState?.crossTrackError ?? 0,
    surface: car.trackState?.surface ?? 'track',
    wheels: serializeWheels(car.wheelStates),
    inPitLane: Boolean(car.trackState?.inPitLane),
    pitLanePart: car.trackState?.pitLanePart ?? null,
    pitBoxId: car.trackState?.pitBoxId ?? null,
    pitLaneCrossTrackError: car.trackState?.pitLaneCrossTrackError ?? null,
    contactCooldown: car.contactCooldown,
    tireEnergy: car.tireEnergy,
    usedTireCompounds: [...(car.usedTireCompounds ?? [])],
    pitIntent: normalizePitIntent(car.pitStop?.intent) ?? PIT_INTENT_NONE,
    pitStop: serializePitStop(car.pitStop),
    positionSource: 'integrated-vehicle',
  };
}

export function serializeRenderCar(car, dependencies) {
  const { serializeRenderPitStop } = dependencies;
  return {
    id: car.id,
    color: car.color,
    previousX: car.previousX ?? car.x,
    previousY: car.previousY ?? car.y,
    x: car.x,
    y: car.y,
    previousHeading: car.previousHeading ?? car.heading,
    heading: car.heading,
    drsActive: Boolean(car.drsActive),
    pitStop: serializeRenderPitStop(car.pitStop),
    interaction: serializeParticipantInteraction(car.interaction),
  };
}

export function serializeObservationCar(car, rank, dependencies) {
  const {
    createLapTelemetry,
    normalizePitIntent,
    PIT_INTENT_NONE,
    serializeLapTelemetry,
    serializeObservationPitStop,
    serializeWheels: serializeWheelState = serializeWheels,
    simSpeedToKph,
  } = dependencies;
  return {
    id: car.id,
    rank,
    previousX: car.previousX ?? car.x,
    previousY: car.previousY ?? car.y,
    x: car.x,
    y: car.y,
    previousHeading: car.previousHeading ?? car.heading,
    heading: car.heading,
    steeringAngle: car.steeringAngle,
    yawRate: car.yawRate,
    speed: car.speed,
    speedKph: simSpeedToKph(car.speed),
    throttle: car.throttle,
    brake: car.brake,
    progress: car.progress,
    raceDistance: car.raceDistance,
    lap: car.lap,
    lapTelemetry: serializeLapTelemetry(car.lapTelemetry ?? createLapTelemetry({ length: 1 }, 0, 0)),
    signedOffset: car.trackState?.signedOffset ?? 0,
    crossTrackError: car.trackState?.crossTrackError ?? 0,
    surface: car.trackState?.surface ?? 'track',
    trackHeadingError: car.trackHeadingError,
    trackState: car.trackState ? {
      distance: car.trackState.distance,
      signedOffset: car.trackState.signedOffset,
      crossTrackError: car.trackState.crossTrackError,
      surface: car.trackState.surface,
      inPitLane: Boolean(car.trackState.inPitLane),
      pitLanePart: car.trackState.pitLanePart ?? null,
      pitBoxId: car.trackState.pitBoxId ?? null,
      curvature: car.trackState.curvature ?? 0,
    } : null,
    wheels: serializeWheelState(car.wheelStates),
    inPitLane: Boolean(car.trackState?.inPitLane),
    pitLanePart: car.trackState?.pitLanePart ?? null,
    pitBoxId: car.trackState?.pitBoxId ?? null,
    tireEnergy: car.tireEnergy ?? null,
    pitIntent: normalizePitIntent(car.pitStop?.intent) ?? PIT_INTENT_NONE,
    pitStop: serializeObservationPitStop(car.pitStop),
    interaction: serializeParticipantInteraction(car.interaction),
  };
}
